import request, { unwrapPage, unwrapResponse, type PageResponse } from '../request'

export type OrderStatus = 'draft' | 'confirmed' | 'in_production' | 'completed' | 'closed'
export interface OrderVO { orderId: number; dingTalkApprovalNo: string; orderCode: string; phoneModel?: string | null; projectType: 'product_line' | 'model_variant'; orderType: 'customer_requirement' | 'market_requirement'; productName: string; status: OrderStatus; projectId: number; closeReason?: string | null; createdAt: string }
export interface OrderQuery { page?: number; size?: number; keyword?: string; status?: string; source?: string }
export interface VariantColorVO { variantColorId: number; colorCode?: string; colorName: string; sourceConfirmedAt?: string; selected: boolean }
export interface MoldCodeMatchVO { moldCode: string; expectedMoldCode: string; productSpecificCode: string; materialCode: string; phoneModelCode: string; matchStatus: 'linked_existing' | 'created_draft'; inventoryId?: number; message?: string }
export interface RequirementFormVO { projectId: number; dingTalkApprovalNo: string; productName: string; model: string; networkType?: string; holeType?: string; mobileFunction?: string; tipo?: string; priority?: string; manufacturingLocation?: string; moldMarking?: string; productSpecificCode?: string; phoneModelCode?: string; materialCodes?: string; moldCodes?: string; moldMatchStatus?: string; moldMatches?: MoldCodeMatchVO[]; referenceUrl?: string; remark?: string; expectedDeliveryDate?: string; requirementType?: 'customer_requirement' | 'market_requirement'; customerRequirement?: string; status: 'draft' | 'confirmed'; colors: VariantColorVO[] }
export interface RequirementFormPayload extends Omit<RequirementFormVO, 'projectId' | 'dingTalkApprovalNo' | 'productName' | 'status' | 'colors' | 'productSpecificCode' | 'phoneModelCode' | 'materialCodes' | 'moldCodes' | 'moldMatchStatus' | 'moldMatches'> { selectedVariantColorIds: number[]; operator?: string }
export interface DingTalkModelVariantPayload { dingTalkApprovalNo: string; approvalStatus: 'approved'; parentProductId: number; model: string; networkType?: string; holeType?: string; mobileFunction?: string; tipo: string; priority?: string; manufacturingLocation?: string; moldMarking?: string; productSpecificCode?: string; phoneModelCode?: string; materialCodes?: string[]; moldCodes?: string; referenceUrl?: string; remark?: string; expectedDeliveryDate?: string; createdBy: string }

export async function getOrders(query: OrderQuery = {}): Promise<PageResponse<OrderVO>> { return unwrapPage<OrderVO>(await request.get('/orders', { params: query })) }
export async function getRequirementForm(projectId: number): Promise<RequirementFormVO> { return unwrapResponse(await request.get(`/projects/${projectId}/requirement-form`)) }
export async function saveRequirementForm(projectId: number, payload: RequirementFormPayload): Promise<RequirementFormVO> { return unwrapResponse(await request.put(`/projects/${projectId}/requirement-form`, payload)) }
export async function confirmRequirementForm(projectId: number, payload: RequirementFormPayload): Promise<RequirementFormVO> { return unwrapResponse(await request.post(`/projects/${projectId}/requirement-form/confirm`, payload)) }
export async function simulateDingTalkApproval(payload: DingTalkModelVariantPayload) { return unwrapResponse(await request.post('/integrations/dingtalk/model-variant-approvals', payload)) }
