services:
  redis:
    volumes:
      - type: bind
        source: ${PLM_STORAGE_ROOT:-/srv/plm-data}/plm_redisdata
        target: /data
        bind:
          create_host_path: false

  server:
    volumes:
      - type: bind
        source: ${PLM_STORAGE_ROOT:-/srv/plm-data}/plm_uploads
        target: /app/data/uploads
        bind:
          create_host_path: false
