-- YUEWEI PLM PostgreSQL schema
-- Scope: PLM only. ERP/MES/WMS/CRM are reserved as mappings/logs, not implemented as formal integrations.

CREATE SCHEMA IF NOT EXISTS plm;
SET search_path TO plm;

CREATE DOMAIN bool_flag AS smallint
  CHECK (VALUE IN (0, 1));

CREATE DOMAIN rate_decimal AS numeric(10,4)
  CHECK (VALUE IS NULL OR VALUE >= 0);

CREATE DOMAIN amount_decimal AS numeric(18,4)
  CHECK (VALUE IS NULL OR VALUE >= 0);

CREATE TABLE plm_customer (
  customer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_code varchar(64) NOT NULL,
  customer_name varchar(255) NOT NULL,
  customer_short_name varchar(128),
  customer_type varchar(64),
  country_code varchar(32),
  contact_name varchar(128),
  contact_phone varchar(64),
  contact_email varchar(128),
  status varchar(32) NOT NULL DEFAULT 'draft',
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_customer_code UNIQUE (customer_code),
  CONSTRAINT ck_plm_customer_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE TABLE sys_user (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_code varchar(64) NOT NULL,
  user_name varchar(128) NOT NULL,
  login_name varchar(128) NOT NULL,
  mobile varchar(64),
  email varchar(128),
  department_name varchar(128),
  status varchar(32) NOT NULL DEFAULT 'draft',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_user_code UNIQUE (user_code),
  CONSTRAINT uk_sys_user_login_name UNIQUE (login_name),
  CONSTRAINT ck_sys_user_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE TABLE sys_role (
  role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code varchar(64) NOT NULL,
  role_name varchar(128) NOT NULL,
  role_type varchar(64),
  status varchar(32) NOT NULL DEFAULT 'draft',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_role_code UNIQUE (role_code),
  CONSTRAINT ck_sys_role_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE TABLE sys_permission (
  permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_code varchar(128) NOT NULL,
  permission_name varchar(128) NOT NULL,
  permission_type varchar(64) NOT NULL,
  resource_type varchar(64),
  resource_path varchar(255),
  action_code varchar(64) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_permission_code UNIQUE (permission_code),
  CONSTRAINT ck_sys_permission_status CHECK (status IN ('draft', 'active', 'inactive')),
  CONSTRAINT ck_sys_permission_type CHECK (permission_type IN ('menu', 'button', 'api', 'data', 'field'))
);

CREATE TABLE sys_user_role (
  user_role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES sys_user(user_id),
  role_id bigint NOT NULL REFERENCES sys_role(role_id),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  CONSTRAINT uk_sys_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE sys_role_permission (
  role_permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id bigint NOT NULL REFERENCES sys_role(role_id),
  permission_id bigint NOT NULL REFERENCES sys_permission(permission_id),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  CONSTRAINT uk_sys_role_permission UNIQUE (role_id, permission_id)
);

CREATE TABLE plm_product (
  product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_product_id bigint REFERENCES plm_product(product_id),
  customer_id bigint REFERENCES plm_customer(customer_id),
  product_code varchar(64) NOT NULL,
  product_name varchar(255) NOT NULL,
  product_type varchar(64) NOT NULL,
  series_name varchar(128),
  model varchar(128),
  color varchar(64),
  material varchar(128),
  package_type varchar(128),
  surface_process varchar(128),
  core_process varchar(255),
  composition text,
  owner_user_id bigint REFERENCES sys_user(user_id),
  version_no varchar(32) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'draft',
  effective_date date,
  released_at timestamp,
  released_by varchar(64),
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_product_code UNIQUE (product_code),
  CONSTRAINT ck_plm_product_type CHECK (product_type IN ('product_line', 'model_variant')),
  CONSTRAINT ck_plm_product_status CHECK (status IN ('draft', 'developing', 'released', 'archived')),
  CONSTRAINT ck_plm_product_variant_parent CHECK (
    product_type <> 'model_variant' OR parent_product_id IS NOT NULL
  )
);

CREATE TABLE plm_order (
  order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code varchar(64) NOT NULL,
  customer_id bigint REFERENCES plm_customer(customer_id),
  product_id bigint REFERENCES plm_product(product_id),
  order_type varchar(64) NOT NULL,
  order_source_type varchar(64),
  order_title varchar(255) NOT NULL,
  quantity numeric(18,4),
  unit varchar(32),
  expected_date date,
  priority_level varchar(32),
  status varchar(32) NOT NULL DEFAULT 'draft',
  source_channel varchar(64),
  requirement_content text,
  customer_confirmed_flag bool_flag NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_order_code UNIQUE (order_code),
  CONSTRAINT ck_plm_order_quantity CHECK (quantity IS NULL OR quantity > 0),
  CONSTRAINT ck_plm_order_type CHECK (order_type IN ('market_requirement', 'customer_requirement', 'sample', 'quote', 'internal')),
  CONSTRAINT ck_plm_order_source_type CHECK (
    order_source_type IS NULL OR order_source_type IN ('customer', 'market', 'internal_plan', 'sales_opportunity', 'management_decision')
  ),
  CONSTRAINT ck_plm_order_status CHECK (status IN ('draft', 'confirmed', 'in_production', 'completed', 'closed'))
);

CREATE TABLE plm_workstation (
  workstation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workstation_code varchar(64) NOT NULL,
  workstation_name varchar(255) NOT NULL,
  workstation_type varchar(64) NOT NULL,
  workshop_name varchar(128),
  capacity_desc varchar(255),
  default_hour_rate amount_decimal,
  status varchar(32) NOT NULL DEFAULT 'draft',
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_workstation_code UNIQUE (workstation_code),
  CONSTRAINT ck_plm_workstation_type CHECK (workstation_type IN ('machine', 'station', 'line', 'work_center')),
  CONSTRAINT ck_plm_workstation_status CHECK (status IN ('draft', 'available', 'in_use', 'maintenance', 'inactive'))
);

CREATE TABLE plm_production_order (
  production_order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_order_code varchar(64) NOT NULL,
  order_id bigint REFERENCES plm_order(order_id),
  product_id bigint NOT NULL REFERENCES plm_product(product_id),
  production_order_type varchar(64) NOT NULL,
  quantity numeric(18,4),
  unit varchar(32),
  planned_start_at timestamp,
  planned_end_at timestamp,
  actual_start_at timestamp,
  actual_end_at timestamp,
  owner_user_id bigint REFERENCES sys_user(user_id),
  status varchar(32) NOT NULL DEFAULT 'draft',
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_production_order_code UNIQUE (production_order_code),
  CONSTRAINT ck_plm_production_order_type CHECK (production_order_type IN ('sample', 'trial', 'mass_prep', 'rework', 'tooling_trial')),
  CONSTRAINT ck_plm_production_order_status CHECK (status IN ('draft', 'scheduled', 'in_progress', 'completed', 'closed')),
  CONSTRAINT ck_plm_production_order_quantity CHECK (quantity IS NULL OR quantity > 0),
  CONSTRAINT ck_plm_production_order_plan_time CHECK (planned_end_at IS NULL OR planned_start_at IS NULL OR planned_end_at >= planned_start_at),
  CONSTRAINT ck_plm_production_order_actual_time CHECK (actual_end_at IS NULL OR actual_start_at IS NULL OR actual_end_at >= actual_start_at)
);

CREATE TABLE plm_process (
  process_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_code varchar(64) NOT NULL,
  product_id bigint REFERENCES plm_product(product_id),
  production_order_id bigint REFERENCES plm_production_order(production_order_id),
  process_name varchar(255) NOT NULL,
  process_type varchar(64) NOT NULL,
  sequence_no integer,
  workstation_id bigint REFERENCES plm_workstation(workstation_id),
  supplier_name varchar(255),
  process_param_json jsonb,
  standard_time_mins amount_decimal,
  hour_rate amount_decimal,
  operating_cost amount_decimal,
  currency_code varchar(16),
  quality_requirement text,
  version_no varchar(32),
  status varchar(32) NOT NULL DEFAULT 'draft',
  effective_date date,
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_process_code UNIQUE (process_code),
  CONSTRAINT ck_plm_process_type CHECK (process_type IN ('routing', 'operation', 'change', 'quality_gate', 'sample_process')),
  CONSTRAINT ck_plm_process_status CHECK (status IN ('draft', 'confirmed', 'locked', 'changed', 'archived')),
  CONSTRAINT ck_plm_process_sequence CHECK (sequence_no IS NULL OR sequence_no > 0)
);

CREATE TABLE plm_inventory (
  inventory_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_code varchar(64) NOT NULL,
  inventory_name varchar(255) NOT NULL,
  inventory_type varchar(64) NOT NULL,
  product_id bigint REFERENCES plm_product(product_id),
  parent_inventory_id bigint REFERENCES plm_inventory(inventory_id),
  item_group_code varchar(64),
  brand_name varchar(128),
  specification varchar(255),
  description text,
  image_attachment_id bigint,
  stock_uom varchar(32) NOT NULL,
  purchase_uom varchar(32),
  sales_uom varchar(32),
  quantity numeric(18,4),
  opening_stock amount_decimal,
  safety_stock amount_decimal,
  min_order_qty amount_decimal,
  lead_time_days integer,
  valuation_rate amount_decimal,
  standard_rate amount_decimal,
  last_purchase_rate amount_decimal,
  unit_cost amount_decimal,
  currency_code varchar(16),
  valuation_method varchar(32),
  loss_rate rate_decimal,
  default_bom_id bigint,
  supplier_name varchar(255),
  is_stock_item bool_flag NOT NULL DEFAULT 0,
  is_purchase_item bool_flag NOT NULL DEFAULT 0,
  is_sales_item bool_flag NOT NULL DEFAULT 0,
  include_item_in_manufacturing bool_flag NOT NULL DEFAULT 1,
  has_batch_no bool_flag NOT NULL DEFAULT 0,
  has_serial_no bool_flag NOT NULL DEFAULT 0,
  has_variants bool_flag NOT NULL DEFAULT 0,
  is_fixed_asset bool_flag NOT NULL DEFAULT 0,
  tooling_cavity_spec varchar(128),
  tooling_life_total bigint,
  tooling_life_used bigint,
  status varchar(32) NOT NULL DEFAULT 'draft',
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_inventory_code UNIQUE (inventory_code),
  CONSTRAINT ck_plm_inventory_type CHECK (inventory_type IN ('material', 'semi_finished', 'finished', 'packaging', 'tooling', 'fixture')),
  CONSTRAINT ck_plm_inventory_status CHECK (status IN ('draft', 'available', 'reserved', 'consumed', 'closed')),
  CONSTRAINT ck_plm_inventory_quantity CHECK (quantity IS NULL OR quantity >= 0),
  CONSTRAINT ck_plm_inventory_lead_time CHECK (lead_time_days IS NULL OR lead_time_days >= 0),
  CONSTRAINT ck_plm_inventory_tooling_life CHECK (
    tooling_life_used IS NULL OR tooling_life_total IS NULL OR tooling_life_used <= tooling_life_total
  ),
  CONSTRAINT ck_plm_inventory_valuation_method CHECK (
    valuation_method IS NULL OR valuation_method IN ('fifo', 'moving_average', 'lifo')
  )
);

CREATE TABLE plm_product_attr (
  product_attr_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES plm_product(product_id),
  attr_group varchar(64) NOT NULL,
  attr_key varchar(64) NOT NULL,
  attr_value text,
  sort_no integer,
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_product_attr UNIQUE (product_id, attr_group, attr_key),
  CONSTRAINT ck_plm_product_attr_status CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE TABLE plm_product_cost (
  product_cost_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES plm_product(product_id),
  version_no varchar(32) NOT NULL,
  currency_code varchar(16) NOT NULL,
  material_cost amount_decimal,
  process_cost amount_decimal,
  package_cost amount_decimal,
  labor_cost amount_decimal,
  tooling_cost amount_decimal,
  loss_cost amount_decimal,
  management_fee amount_decimal,
  profit_rate rate_decimal,
  total_cost amount_decimal,
  status varchar(32) NOT NULL DEFAULT 'draft',
  effective_date date,
  released_at timestamp,
  released_by varchar(64),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_product_cost_version UNIQUE (product_id, version_no, currency_code),
  CONSTRAINT ck_plm_product_cost_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'))
);

CREATE TABLE plm_product_quality_record (
  product_quality_record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES plm_product(product_id),
  production_order_id bigint REFERENCES plm_production_order(production_order_id),
  process_id bigint REFERENCES plm_process(process_id),
  quality_type varchar(64) NOT NULL,
  test_item varchar(128),
  test_result varchar(64),
  standard_name varchar(255),
  issue_desc text,
  corrective_action text,
  expiry_date date,
  version_no varchar(32),
  status varchar(32) NOT NULL DEFAULT 'draft',
  effective_date date,
  released_at timestamp,
  released_by varchar(64),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_product_quality_type CHECK (quality_type IN ('test', 'inspection', 'compliance', 'customer_feedback')),
  CONSTRAINT ck_plm_product_quality_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'))
);

CREATE TABLE plm_order_quote (
  order_quote_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES plm_order(order_id),
  product_id bigint NOT NULL REFERENCES plm_product(product_id),
  quantity numeric(18,4),
  currency_code varchar(16) NOT NULL,
  exchange_rate numeric(18,6),
  quoted_price amount_decimal,
  total_amount amount_decimal,
  status varchar(32) NOT NULL DEFAULT 'draft',
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_order_quote_quantity CHECK (quantity IS NULL OR quantity > 0),
  CONSTRAINT ck_plm_order_quote_exchange_rate CHECK (exchange_rate IS NULL OR exchange_rate > 0),
  CONSTRAINT ck_plm_order_quote_status CHECK (status IN ('draft', 'confirmed', 'in_production', 'completed', 'closed'))
);

CREATE TABLE plm_process_change_record (
  process_change_record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_id bigint NOT NULL REFERENCES plm_process(process_id),
  product_id bigint NOT NULL REFERENCES plm_product(product_id),
  change_type varchar(64) NOT NULL,
  change_reason text NOT NULL,
  impact_scope text,
  risk_level varchar(32),
  old_version_no varchar(32),
  new_version_no varchar(32),
  effective_date date,
  status varchar(32) NOT NULL DEFAULT 'draft',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_process_change_status CHECK (status IN ('draft', 'confirmed', 'locked', 'changed', 'archived')),
  CONSTRAINT ck_plm_process_change_risk CHECK (risk_level IS NULL OR risk_level IN ('low', 'medium', 'high', 'critical'))
);

CREATE TABLE plm_product_bom (
  product_bom_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES plm_product(product_id),
  bom_code varchar(64) NOT NULL,
  bom_type varchar(64) NOT NULL,
  inventory_id bigint REFERENCES plm_inventory(inventory_id),
  bom_name varchar(255),
  quantity numeric(18,4) NOT NULL,
  uom_code varchar(32),
  company_code varchar(64),
  is_active bool_flag NOT NULL DEFAULT 1,
  is_default bool_flag NOT NULL DEFAULT 0,
  with_operations bool_flag NOT NULL DEFAULT 0,
  currency_code varchar(16),
  conversion_rate numeric(18,6),
  material_cost_mode varchar(32),
  buying_price_list_code varchar(64),
  routing_code varchar(64),
  raw_material_cost amount_decimal,
  operating_cost amount_decimal,
  total_cost amount_decimal,
  base_total_cost amount_decimal,
  process_loss_percentage rate_decimal,
  process_loss_quantity numeric(18,4),
  default_source_warehouse_code varchar(64),
  default_target_warehouse_code varchar(64),
  is_phantom_bom bool_flag NOT NULL DEFAULT 0,
  version_no varchar(32) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'draft',
  effective_date date,
  released_at timestamp,
  released_by varchar(64),
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_product_bom_code UNIQUE (bom_code),
  CONSTRAINT uk_plm_product_bom_version UNIQUE (product_id, bom_type, version_no),
  CONSTRAINT ck_plm_product_bom_type CHECK (bom_type IN ('ebom', 'mbom', 'packaging_bom')),
  CONSTRAINT ck_plm_product_bom_quantity CHECK (quantity > 0),
  CONSTRAINT ck_plm_product_bom_conversion_rate CHECK (conversion_rate IS NULL OR conversion_rate > 0),
  CONSTRAINT ck_plm_product_bom_loss_quantity CHECK (process_loss_quantity IS NULL OR process_loss_quantity >= 0),
  CONSTRAINT ck_plm_product_bom_material_cost_mode CHECK (
    material_cost_mode IS NULL OR material_cost_mode IN ('valuation_rate', 'last_purchase_rate', 'price_list')
  ),
  CONSTRAINT ck_plm_product_bom_status CHECK (status IN ('draft', 'frozen', 'released', 'archived'))
);

ALTER TABLE plm_inventory
  ADD CONSTRAINT fk_plm_inventory_default_bom
  FOREIGN KEY (default_bom_id) REFERENCES plm_product_bom(product_bom_id);

CREATE TABLE plm_product_bom_item (
  product_bom_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_bom_id bigint NOT NULL REFERENCES plm_product_bom(product_bom_id),
  product_id bigint NOT NULL REFERENCES plm_product(product_id),
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  child_bom_id bigint REFERENCES plm_product_bom(product_bom_id),
  line_no integer NOT NULL,
  parent_line_no integer,
  source_warehouse_code varchar(64),
  description text,
  quantity numeric(18,4) NOT NULL,
  uom_code varchar(32) NOT NULL,
  stock_quantity numeric(18,4),
  stock_uom_code varchar(32),
  conversion_factor numeric(18,6),
  rate amount_decimal,
  amount amount_decimal,
  quantity_per_unit numeric(18,6),
  loss_rate rate_decimal,
  include_item_in_manufacturing bool_flag NOT NULL DEFAULT 1,
  do_not_explode bool_flag NOT NULL DEFAULT 0,
  is_sub_assembly_item bool_flag NOT NULL DEFAULT 0,
  substitute_flag bool_flag NOT NULL DEFAULT 0,
  version_no varchar(32) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'draft',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_product_bom_item_line UNIQUE (product_bom_id, line_no),
  CONSTRAINT ck_plm_product_bom_item_line CHECK (line_no > 0),
  CONSTRAINT ck_plm_product_bom_item_quantity CHECK (quantity > 0),
  CONSTRAINT ck_plm_product_bom_item_stock_quantity CHECK (stock_quantity IS NULL OR stock_quantity >= 0),
  CONSTRAINT ck_plm_product_bom_item_conversion CHECK (conversion_factor IS NULL OR conversion_factor > 0),
  CONSTRAINT ck_plm_product_bom_item_quantity_per_unit CHECK (quantity_per_unit IS NULL OR quantity_per_unit >= 0),
  CONSTRAINT ck_plm_product_bom_item_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'))
);

CREATE TABLE plm_product_bom_operation (
  product_bom_operation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_bom_id bigint NOT NULL REFERENCES plm_product_bom(product_bom_id),
  process_id bigint REFERENCES plm_process(process_id),
  workstation_id bigint REFERENCES plm_workstation(workstation_id),
  sequence_no integer,
  time_in_mins amount_decimal,
  hour_rate amount_decimal,
  operating_cost amount_decimal,
  status varchar(32) NOT NULL DEFAULT 'draft',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_product_bom_operation_sequence CHECK (sequence_no IS NULL OR sequence_no > 0),
  CONSTRAINT ck_plm_product_bom_operation_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'))
);

CREATE TABLE plm_product_bom_exploded_item (
  product_bom_exploded_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_bom_id bigint NOT NULL REFERENCES plm_product_bom(product_bom_id),
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  source_warehouse_code varchar(64),
  stock_quantity numeric(18,4),
  stock_uom_code varchar(32),
  rate amount_decimal,
  amount amount_decimal,
  quantity_per_unit numeric(18,6),
  include_item_in_manufacturing bool_flag NOT NULL DEFAULT 1,
  is_sub_assembly_item bool_flag NOT NULL DEFAULT 0,
  status varchar(32) NOT NULL DEFAULT 'draft',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_product_bom_exploded_stock_quantity CHECK (stock_quantity IS NULL OR stock_quantity >= 0),
  CONSTRAINT ck_plm_product_bom_exploded_quantity_per_unit CHECK (quantity_per_unit IS NULL OR quantity_per_unit >= 0),
  CONSTRAINT ck_plm_product_bom_exploded_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'))
);

CREATE TABLE plm_inventory_barcode (
  inventory_barcode_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  barcode varchar(128) NOT NULL,
  barcode_type varchar(32),
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_inventory_barcode UNIQUE (barcode),
  CONSTRAINT ck_plm_inventory_barcode_status CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE TABLE plm_inventory_uom_conversion (
  inventory_uom_conversion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  uom_code varchar(32) NOT NULL,
  conversion_factor numeric(18,6) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_inventory_uom_conversion UNIQUE (inventory_id, uom_code),
  CONSTRAINT ck_plm_inventory_uom_conversion_factor CHECK (conversion_factor > 0),
  CONSTRAINT ck_plm_inventory_uom_conversion_status CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE TABLE plm_inventory_default (
  inventory_default_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  company_code varchar(64),
  default_warehouse_code varchar(64),
  default_supplier_code varchar(64),
  expense_account_code varchar(64),
  income_account_code varchar(64),
  inventory_account_code varchar(64),
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_inventory_default UNIQUE (inventory_id, company_code),
  CONSTRAINT ck_plm_inventory_default_status CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE TABLE plm_inventory_supplier_item (
  inventory_supplier_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  supplier_code varchar(64) NOT NULL,
  supplier_item_code varchar(128),
  supplier_item_name varchar(255),
  min_order_qty amount_decimal,
  lead_time_days integer,
  last_purchase_rate amount_decimal,
  currency_code varchar(16),
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_inventory_supplier_item UNIQUE (inventory_id, supplier_code),
  CONSTRAINT ck_plm_inventory_supplier_item_lead_time CHECK (lead_time_days IS NULL OR lead_time_days >= 0),
  CONSTRAINT ck_plm_inventory_supplier_item_status CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE TABLE plm_inventory_reorder_rule (
  inventory_reorder_rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  warehouse_code varchar(64),
  reorder_level amount_decimal,
  reorder_quantity amount_decimal,
  material_request_type varchar(32),
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_inventory_reorder_rule UNIQUE (inventory_id, warehouse_code),
  CONSTRAINT ck_plm_inventory_reorder_rule_type CHECK (
    material_request_type IS NULL OR material_request_type IN ('purchase', 'transfer', 'material_issue', 'manufacture')
  ),
  CONSTRAINT ck_plm_inventory_reorder_rule_status CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE TABLE plm_attachment (
  attachment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_object_type varchar(64) NOT NULL,
  owner_object_id bigint NOT NULL,
  file_category varchar(64) NOT NULL,
  file_name varchar(255) NOT NULL,
  file_ext varchar(32),
  storage_key varchar(512) NOT NULL,
  file_size bigint,
  mime_type varchar(128),
  checksum varchar(128),
  version_no varchar(32),
  status varchar(32) NOT NULL DEFAULT 'draft',
  effective_date date,
  released_at timestamp,
  released_by varchar(64),
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_attachment_owner_type CHECK (owner_object_type IN ('Customer', 'Product', 'Order', 'ProductionOrder', 'Process', 'Inventory', 'Workstation')),
  CONSTRAINT ck_plm_attachment_file_size CHECK (file_size IS NULL OR file_size >= 0),
  CONSTRAINT ck_plm_attachment_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'))
);

ALTER TABLE plm_inventory
  ADD CONSTRAINT fk_plm_inventory_image_attachment
  FOREIGN KEY (image_attachment_id) REFERENCES plm_attachment(attachment_id);

CREATE TABLE plm_attachment_download_log (
  attachment_download_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attachment_id bigint NOT NULL REFERENCES plm_attachment(attachment_id),
  download_user_id bigint REFERENCES sys_user(user_id),
  download_user_name varchar(128),
  download_ip varchar(64),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE plm_approval_definition (
  approval_definition_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approval_code varchar(64) NOT NULL,
  approval_name varchar(128) NOT NULL,
  object_type varchar(64) NOT NULL,
  version_no varchar(32) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'draft',
  config_json jsonb NOT NULL,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_approval_definition_code_version UNIQUE (approval_code, version_no),
  CONSTRAINT ck_plm_approval_definition_object_type CHECK (object_type IN ('Customer', 'Product', 'Order', 'ProductionOrder', 'Process', 'Inventory', 'Workstation', 'Attachment')),
  CONSTRAINT ck_plm_approval_definition_status CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE TABLE plm_approval_instance (
  approval_instance_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approval_definition_id bigint REFERENCES plm_approval_definition(approval_definition_id),
  object_type varchar(64) NOT NULL,
  object_id bigint NOT NULL,
  current_node_code varchar(64),
  status varchar(32) NOT NULL DEFAULT 'draft',
  start_user_id bigint REFERENCES sys_user(user_id),
  started_at timestamp,
  ended_at timestamp,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_approval_instance_object_type CHECK (object_type IN ('Customer', 'Product', 'Order', 'ProductionOrder', 'Process', 'Inventory', 'Workstation', 'Attachment')),
  CONSTRAINT ck_plm_approval_instance_status CHECK (status IN ('draft', 'in_progress', 'approved', 'rejected', 'cancelled', 'closed')),
  CONSTRAINT ck_plm_approval_instance_time CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE plm_approval_task (
  approval_task_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approval_instance_id bigint NOT NULL REFERENCES plm_approval_instance(approval_instance_id),
  node_code varchar(64) NOT NULL,
  approver_user_id bigint REFERENCES sys_user(user_id),
  approver_user_name varchar(128),
  action_type varchar(64),
  action_comment text,
  status varchar(32) NOT NULL DEFAULT 'pending',
  acted_at timestamp,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_approval_task_action_type CHECK (
    action_type IS NULL OR action_type IN ('approve', 'reject', 'transfer', 'cancel', 'comment')
  ),
  CONSTRAINT ck_plm_approval_task_status CHECK (status IN ('pending', 'approved', 'rejected', 'transferred', 'cancelled'))
);

CREATE TABLE plm_operation_log (
  operation_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_type varchar(64) NOT NULL,
  object_id bigint NOT NULL,
  action_type varchar(64) NOT NULL,
  before_snapshot jsonb,
  after_snapshot jsonb,
  operator_user_id bigint REFERENCES sys_user(user_id),
  operator_user_name varchar(128),
  operator_ip varchar(64),
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_plm_operation_log_object_type CHECK (object_type IN ('Customer', 'Product', 'Order', 'ProductionOrder', 'Process', 'Inventory', 'Workstation', 'Attachment', 'Approval', 'System')),
  CONSTRAINT ck_plm_operation_log_action CHECK (action_type IN ('create', 'update', 'delete', 'submit', 'approve', 'reject', 'freeze', 'publish', 'void', 'download', 'import', 'retry', 'compensate'))
);

CREATE TABLE plm_import_batch (
  import_batch_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_type varchar(64) NOT NULL,
  file_name varchar(255) NOT NULL,
  total_count integer NOT NULL DEFAULT 0,
  success_count integer NOT NULL DEFAULT 0,
  fail_count integer NOT NULL DEFAULT 0,
  status varchar(32) NOT NULL DEFAULT 'draft',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_import_batch_object_type CHECK (object_type IN ('Customer', 'Product', 'Order', 'ProductionOrder', 'Process', 'Inventory', 'Workstation')),
  CONSTRAINT ck_plm_import_batch_counts CHECK (total_count >= 0 AND success_count >= 0 AND fail_count >= 0),
  CONSTRAINT ck_plm_import_batch_status CHECK (status IN ('draft', 'confirmed', 'in_production', 'completed', 'closed'))
);

CREATE TABLE plm_import_detail (
  import_detail_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch_id bigint NOT NULL REFERENCES plm_import_batch(import_batch_id),
  row_no integer NOT NULL,
  business_key varchar(128),
  raw_data jsonb,
  status varchar(32) NOT NULL DEFAULT 'draft',
  error_message text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_plm_import_detail_row_no CHECK (row_no > 0),
  CONSTRAINT ck_plm_import_detail_status CHECK (status IN ('draft', 'confirmed', 'in_production', 'completed', 'closed'))
);

CREATE TABLE plm_integration_mapping (
  integration_mapping_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_object_type varchar(64) NOT NULL,
  source_object_id bigint NOT NULL,
  target_system_code varchar(64) NOT NULL,
  target_object_code varchar(128) NOT NULL,
  target_object_name varchar(255),
  version_no varchar(32) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'draft',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_integration_mapping UNIQUE (source_object_type, source_object_id, target_system_code, target_object_code, version_no),
  CONSTRAINT ck_plm_integration_mapping_source_type CHECK (source_object_type IN ('Customer', 'Product', 'Order', 'ProductionOrder', 'Process', 'Inventory', 'Workstation')),
  CONSTRAINT ck_plm_integration_mapping_status CHECK (status IN ('draft', 'active', 'inactive', 'archived'))
);

CREATE TABLE plm_integration_log (
  integration_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_object_type varchar(64) NOT NULL,
  source_object_id bigint NOT NULL,
  target_system_code varchar(64) NOT NULL,
  request_payload jsonb,
  response_payload jsonb,
  idempotency_key varchar(255) NOT NULL,
  retry_count integer NOT NULL DEFAULT 0,
  status varchar(32) NOT NULL DEFAULT 'draft',
  error_message text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_integration_log_idempotency UNIQUE (idempotency_key),
  CONSTRAINT ck_plm_integration_log_source_type CHECK (source_object_type IN ('Customer', 'Product', 'Order', 'ProductionOrder', 'Process', 'Inventory', 'Workstation')),
  CONSTRAINT ck_plm_integration_log_retry CHECK (retry_count >= 0),
  CONSTRAINT ck_plm_integration_log_status CHECK (status IN ('draft', 'confirmed', 'in_production', 'completed', 'closed', 'failed'))
);

CREATE TABLE sys_dict_type (
  dict_type_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_type_code varchar(64) NOT NULL,
  dict_type_name varchar(128) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'active',
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_dict_type_code UNIQUE (dict_type_code),
  CONSTRAINT ck_sys_dict_type_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE TABLE sys_dict_item (
  dict_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_type_code varchar(64) NOT NULL,
  item_code varchar(64) NOT NULL,
  item_name varchar(128) NOT NULL,
  sort_no integer NOT NULL DEFAULT 0,
  status varchar(32) NOT NULL DEFAULT 'active',
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_dict_item UNIQUE (dict_type_code, item_code),
  CONSTRAINT ck_sys_dict_item_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE TABLE sys_code_rule (
  code_rule_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_type varchar(64) NOT NULL,
  rule_code varchar(64) NOT NULL,
  rule_name varchar(128) NOT NULL,
  prefix_pattern varchar(128) NOT NULL,
  date_pattern varchar(32),
  sequence_length integer NOT NULL DEFAULT 4,
  current_sequence bigint NOT NULL DEFAULT 0,
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_code_rule UNIQUE (object_type, rule_code),
  CONSTRAINT ck_sys_code_rule_sequence_length CHECK (sequence_length > 0),
  CONSTRAINT ck_sys_code_rule_current_sequence CHECK (current_sequence >= 0),
  CONSTRAINT ck_sys_code_rule_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE TABLE sys_system_config (
  system_config_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key varchar(128) NOT NULL,
  config_value text,
  config_name varchar(128),
  config_group varchar(64),
  status varchar(32) NOT NULL DEFAULT 'active',
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_sys_system_config_key UNIQUE (config_key),
  CONSTRAINT ck_sys_system_config_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE INDEX idx_plm_customer_name ON plm_customer(customer_name);
CREATE INDEX idx_plm_customer_status ON plm_customer(status);

CREATE INDEX idx_plm_product_parent ON plm_product(parent_product_id);
CREATE INDEX idx_plm_product_customer ON plm_product(customer_id);
CREATE INDEX idx_plm_product_status ON plm_product(status);
CREATE INDEX idx_plm_product_model_color ON plm_product(model, color);

CREATE INDEX idx_plm_order_customer ON plm_order(customer_id);
CREATE INDEX idx_plm_order_product ON plm_order(product_id);
CREATE INDEX idx_plm_order_type_status ON plm_order(order_type, status);

CREATE INDEX idx_plm_production_order_order ON plm_production_order(order_id);
CREATE INDEX idx_plm_production_order_product ON plm_production_order(product_id);
CREATE INDEX idx_plm_production_order_type_status ON plm_production_order(production_order_type, status);

CREATE INDEX idx_plm_process_product ON plm_process(product_id);
CREATE INDEX idx_plm_process_production_order ON plm_process(production_order_id);
CREATE INDEX idx_plm_process_workstation ON plm_process(workstation_id);
CREATE INDEX idx_plm_process_type_status ON plm_process(process_type, status);
CREATE INDEX idx_plm_process_sequence ON plm_process(product_id, sequence_no);

CREATE INDEX idx_plm_inventory_product ON plm_inventory(product_id);
CREATE INDEX idx_plm_inventory_type_status ON plm_inventory(inventory_type, status);
CREATE INDEX idx_plm_inventory_group ON plm_inventory(item_group_code);
CREATE INDEX idx_plm_inventory_parent ON plm_inventory(parent_inventory_id);

CREATE INDEX idx_plm_workstation_type_status ON plm_workstation(workstation_type, status);

CREATE INDEX idx_plm_product_bom_product ON plm_product_bom(product_id, bom_type, version_no);
CREATE INDEX idx_plm_product_bom_inventory ON plm_product_bom(inventory_id);
CREATE INDEX idx_plm_product_bom_item_bom ON plm_product_bom_item(product_bom_id);
CREATE INDEX idx_plm_product_bom_item_inventory ON plm_product_bom_item(inventory_id);
CREATE INDEX idx_plm_product_bom_operation_bom ON plm_product_bom_operation(product_bom_id);
CREATE INDEX idx_plm_product_bom_exploded_bom ON plm_product_bom_exploded_item(product_bom_id);

CREATE INDEX idx_plm_attachment_owner ON plm_attachment(owner_object_type, owner_object_id);
CREATE INDEX idx_plm_attachment_category ON plm_attachment(file_category, status);
CREATE INDEX idx_plm_attachment_checksum ON plm_attachment(checksum);

CREATE INDEX idx_plm_approval_instance_object ON plm_approval_instance(object_type, object_id);
CREATE INDEX idx_plm_approval_task_instance ON plm_approval_task(approval_instance_id);
CREATE INDEX idx_plm_approval_task_approver ON plm_approval_task(approver_user_id, status);

CREATE INDEX idx_plm_operation_log_object ON plm_operation_log(object_type, object_id);
CREATE INDEX idx_plm_operation_log_created_at ON plm_operation_log(created_at);

CREATE INDEX idx_plm_import_detail_batch ON plm_import_detail(import_batch_id);
CREATE INDEX idx_plm_integration_mapping_source ON plm_integration_mapping(source_object_type, source_object_id);
CREATE INDEX idx_plm_integration_log_source ON plm_integration_log(source_object_type, source_object_id);
CREATE INDEX idx_plm_integration_log_status ON plm_integration_log(status);

COMMENT ON TABLE plm_customer IS 'Customer core object: customer, demand source, confirmation owner.';
COMMENT ON TABLE plm_product IS 'Product core object: product line, model variant, color, version, BOM/file/quality data owner.';
COMMENT ON TABLE plm_order IS 'Order core object: customer demand, sample demand, quote demand, internal demand.';
COMMENT ON TABLE plm_production_order IS 'ProductionOrder core object: sample, trial, tooling trial, rework, mass preparation task.';
COMMENT ON TABLE plm_process IS 'Process core object: process route, operation, process parameter, quality gate, engineering change.';
COMMENT ON TABLE plm_inventory IS 'Inventory core object: material, semi-finished, finished, packaging, tooling, fixture.';
COMMENT ON TABLE plm_workstation IS 'Workstation core object: machine, station, line, work center.';
COMMENT ON TABLE plm_product_bom IS 'Product BOM header as Product versioned data, not an independent root object.';
COMMENT ON TABLE plm_product_bom_item IS 'Product BOM component detail as Product/Inventory extension, not BOMLine root object.';
COMMENT ON TABLE plm_attachment IS 'Attachment metadata for seven core objects; file content is stored in MinIO/S3.';
COMMENT ON TABLE plm_integration_mapping IS 'Reserved external system mapping, not formal ERP/MES integration.';
COMMENT ON TABLE plm_integration_log IS 'Reserved external system integration log, not IntegrationJob root object.';
