-- ERP Item/BOM alignment reserved fields.
-- Scope: mapping-friendly PLM fields only; no formal ERP inventory, purchase, tax, or accounting workflow is implemented.

SET search_path TO plm;

ALTER TABLE plm_inventory
  ADD COLUMN IF NOT EXISTS disabled_flag bool_flag NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS item_group_name varchar(128),
  ADD COLUMN IF NOT EXISTS brand_code varchar(64),
  ADD COLUMN IF NOT EXISTS default_bom_code varchar(64),
  ADD COLUMN IF NOT EXISTS erp_item_reference jsonb;

COMMENT ON COLUMN plm_inventory.disabled_flag IS 'ERP Item disabled reserved flag; PLM lifecycle still uses status.';
COMMENT ON COLUMN plm_inventory.item_group_name IS 'ERP Item Group name snapshot reserved for later mapping.';
COMMENT ON COLUMN plm_inventory.brand_code IS 'ERP Brand code reserved for later mapping.';
COMMENT ON COLUMN plm_inventory.default_bom_code IS 'ERP default_bom code snapshot reserved for later mapping.';
COMMENT ON COLUMN plm_inventory.erp_item_reference IS 'Non-authoritative ERP Item reference payload for mapping review.';

ALTER TABLE plm_inventory_default
  ADD COLUMN IF NOT EXISTS company_name varchar(128),
  ADD COLUMN IF NOT EXISTS default_warehouse_name varchar(128),
  ADD COLUMN IF NOT EXISTS default_supplier_name varchar(255),
  ADD COLUMN IF NOT EXISTS expense_account_name varchar(255),
  ADD COLUMN IF NOT EXISTS income_account_name varchar(255),
  ADD COLUMN IF NOT EXISTS inventory_account_name varchar(255);

ALTER TABLE plm_inventory_reorder_rule
  ADD COLUMN IF NOT EXISTS warehouse_name varchar(128),
  ADD COLUMN IF NOT EXISTS warehouse_reorder_level numeric(18,4),
  ADD COLUMN IF NOT EXISTS warehouse_reorder_quantity numeric(18,4);

UPDATE plm_inventory_reorder_rule
SET warehouse_reorder_level = reorder_level
WHERE warehouse_reorder_level IS NULL AND reorder_level IS NOT NULL;

UPDATE plm_inventory_reorder_rule
SET warehouse_reorder_quantity = reorder_quantity
WHERE warehouse_reorder_quantity IS NULL AND reorder_quantity IS NOT NULL;

CREATE TABLE IF NOT EXISTS plm_inventory_tax (
  inventory_tax_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  tax_template_code varchar(64) NOT NULL,
  tax_template_name varchar(255),
  tax_category varchar(64),
  valid_from date,
  valid_to date,
  status varchar(32) NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL DEFAULT 'system',
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL DEFAULT 'system',
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT uk_plm_inventory_tax UNIQUE (inventory_id, tax_template_code),
  CONSTRAINT ck_plm_inventory_tax_status CHECK (status IN ('draft', 'active', 'inactive', 'archived')),
  CONSTRAINT ck_plm_inventory_tax_valid_date CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from)
);

COMMENT ON TABLE plm_inventory_tax IS 'Inventory tax template reserved child table for ERP Item Tax mapping; not a PLM tax workflow.';

ALTER TABLE plm_product_bom
  ADD COLUMN IF NOT EXISTS output_inventory_code varchar(64),
  ADD COLUMN IF NOT EXISTS output_inventory_name varchar(255),
  ADD COLUMN IF NOT EXISTS company_name varchar(128),
  ADD COLUMN IF NOT EXISTS project_code varchar(64),
  ADD COLUMN IF NOT EXISTS project_name varchar(255),
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS erp_bom_reference jsonb;

UPDATE plm_product_bom b
SET output_inventory_code = i.inventory_code
FROM plm_inventory i
WHERE b.inventory_id = i.inventory_id
  AND b.output_inventory_code IS NULL;

UPDATE plm_product_bom b
SET output_inventory_name = i.inventory_name
FROM plm_inventory i
WHERE b.inventory_id = i.inventory_id
  AND b.output_inventory_name IS NULL;

COMMENT ON COLUMN plm_product_bom.output_inventory_code IS 'Manufactured Item code snapshot for ERP BOM.item mapping.';
COMMENT ON COLUMN plm_product_bom.output_inventory_name IS 'Manufactured Item name snapshot for ERP BOM.item_name mapping.';
COMMENT ON COLUMN plm_product_bom.project_code IS 'ERP Project code reserved for later mapping; not a PLM Project root object.';
COMMENT ON COLUMN plm_product_bom.erp_bom_reference IS 'Non-authoritative ERP BOM reference payload for mapping review.';

ALTER TABLE plm_product_bom_item
  ADD COLUMN IF NOT EXISTS item_code varchar(64),
  ADD COLUMN IF NOT EXISTS item_name varchar(255),
  ADD COLUMN IF NOT EXISTS child_bom_code varchar(64),
  ADD COLUMN IF NOT EXISTS source_warehouse_name varchar(128),
  ADD COLUMN IF NOT EXISTS currency_code varchar(16);

UPDATE plm_product_bom_item bi
SET item_code = i.inventory_code
FROM plm_inventory i
WHERE bi.inventory_id = i.inventory_id
  AND bi.item_code IS NULL;

UPDATE plm_product_bom_item bi
SET item_name = i.inventory_name
FROM plm_inventory i
WHERE bi.inventory_id = i.inventory_id
  AND bi.item_name IS NULL;

UPDATE plm_product_bom_item bi
SET child_bom_code = b.bom_code
FROM plm_product_bom b
WHERE bi.child_bom_id = b.product_bom_id
  AND bi.child_bom_code IS NULL;

COMMENT ON COLUMN plm_product_bom_item.item_code IS 'Component Item code snapshot for ERP BOM Item.item_code mapping.';
COMMENT ON COLUMN plm_product_bom_item.item_name IS 'Component Item name snapshot for ERP BOM Item.item_name mapping.';
COMMENT ON COLUMN plm_product_bom_item.child_bom_code IS 'Child BOM code snapshot for ERP BOM Item.bom_no mapping.';

ALTER TABLE plm_product_bom_operation
  ADD COLUMN IF NOT EXISTS operation_code varchar(64),
  ADD COLUMN IF NOT EXISTS operation_name varchar(255),
  ADD COLUMN IF NOT EXISTS workstation_code varchar(64),
  ADD COLUMN IF NOT EXISTS workstation_name varchar(255),
  ADD COLUMN IF NOT EXISTS currency_code varchar(16);

UPDATE plm_product_bom_operation bo
SET operation_code = p.process_code
FROM plm_process p
WHERE bo.process_id = p.process_id
  AND bo.operation_code IS NULL;

UPDATE plm_product_bom_operation bo
SET operation_name = p.process_name
FROM plm_process p
WHERE bo.process_id = p.process_id
  AND bo.operation_name IS NULL;

UPDATE plm_product_bom_operation bo
SET workstation_code = w.workstation_code
FROM plm_workstation w
WHERE bo.workstation_id = w.workstation_id
  AND bo.workstation_code IS NULL;

UPDATE plm_product_bom_operation bo
SET workstation_name = w.workstation_name
FROM plm_workstation w
WHERE bo.workstation_id = w.workstation_id
  AND bo.workstation_name IS NULL;

COMMENT ON COLUMN plm_product_bom_operation.operation_code IS 'Process code snapshot for ERP BOM Operation.operation mapping.';
COMMENT ON COLUMN plm_product_bom_operation.operation_name IS 'Process name snapshot for ERP BOM Operation.operation mapping.';

ALTER TABLE plm_product_bom_exploded_item
  ADD COLUMN IF NOT EXISTS item_code varchar(64),
  ADD COLUMN IF NOT EXISTS item_name varchar(255),
  ADD COLUMN IF NOT EXISTS source_warehouse_name varchar(128),
  ADD COLUMN IF NOT EXISTS currency_code varchar(16);

UPDATE plm_product_bom_exploded_item be
SET item_code = i.inventory_code
FROM plm_inventory i
WHERE be.inventory_id = i.inventory_id
  AND be.item_code IS NULL;

UPDATE plm_product_bom_exploded_item be
SET item_name = i.inventory_name
FROM plm_inventory i
WHERE be.inventory_id = i.inventory_id
  AND be.item_name IS NULL;

COMMENT ON COLUMN plm_product_bom_exploded_item.item_code IS 'Exploded Item code snapshot for ERP BOM Explosion Item.item_code mapping.';
COMMENT ON COLUMN plm_product_bom_exploded_item.item_name IS 'Exploded Item name snapshot for ERP BOM Explosion Item.item_name mapping.';

ALTER TABLE plm_integration_mapping
  ADD COLUMN IF NOT EXISTS source_object_code varchar(128),
  ADD COLUMN IF NOT EXISTS source_object_version_no varchar(32),
  ADD COLUMN IF NOT EXISTS target_object_type varchar(64),
  ADD COLUMN IF NOT EXISTS mapping_payload jsonb;

ALTER TABLE plm_integration_log
  ADD COLUMN IF NOT EXISTS source_object_code varchar(128),
  ADD COLUMN IF NOT EXISTS action_type varchar(64),
  ADD COLUMN IF NOT EXISTS request_digest varchar(128),
  ADD COLUMN IF NOT EXISTS response_digest varchar(128);

CREATE INDEX IF NOT EXISTS idx_plm_inventory_tax_inventory ON plm_inventory_tax(inventory_id);
CREATE INDEX IF NOT EXISTS idx_plm_inventory_default_company ON plm_inventory_default(company_code);
CREATE INDEX IF NOT EXISTS idx_plm_product_bom_output_inventory_code ON plm_product_bom(output_inventory_code);
CREATE INDEX IF NOT EXISTS idx_plm_product_bom_item_item_code ON plm_product_bom_item(item_code);
CREATE INDEX IF NOT EXISTS idx_plm_product_bom_exploded_item_code ON plm_product_bom_exploded_item(item_code);
