-- Workflow, locking, version traceability, import/integration status alignment.
-- Scope: PLM workflow strengthening only; no new root objects and no formal ERP/MES closed-loop implementation.

SET search_path TO plm;

-- 1. Versioned business data: explicit freeze metadata.
ALTER TABLE plm_product
  ADD COLUMN IF NOT EXISTS frozen_at timestamp,
  ADD COLUMN IF NOT EXISTS frozen_by varchar(64),
  ADD COLUMN IF NOT EXISTS freeze_reason text,
  ADD COLUMN IF NOT EXISTS lock_status varchar(32) NOT NULL DEFAULT 'unlocked',
  ADD COLUMN IF NOT EXISTS lock_reason text,
  ADD COLUMN IF NOT EXISTS lock_operator_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS lock_operator_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS lock_operated_at timestamp;

ALTER TABLE plm_process
  ADD COLUMN IF NOT EXISTS released_at timestamp,
  ADD COLUMN IF NOT EXISTS released_by varchar(64),
  ADD COLUMN IF NOT EXISTS frozen_at timestamp,
  ADD COLUMN IF NOT EXISTS frozen_by varchar(64),
  ADD COLUMN IF NOT EXISTS freeze_reason text,
  ADD COLUMN IF NOT EXISTS owner_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS lock_status varchar(32) NOT NULL DEFAULT 'unlocked',
  ADD COLUMN IF NOT EXISTS lock_reason text,
  ADD COLUMN IF NOT EXISTS lock_operator_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS lock_operator_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS lock_operated_at timestamp;

ALTER TABLE plm_product_bom
  ADD COLUMN IF NOT EXISTS frozen_at timestamp,
  ADD COLUMN IF NOT EXISTS frozen_by varchar(64),
  ADD COLUMN IF NOT EXISTS freeze_reason text,
  ADD COLUMN IF NOT EXISTS lock_status varchar(32) NOT NULL DEFAULT 'unlocked',
  ADD COLUMN IF NOT EXISTS lock_reason text,
  ADD COLUMN IF NOT EXISTS lock_operator_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS lock_operator_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS lock_operated_at timestamp;

ALTER TABLE plm_attachment
  ADD COLUMN IF NOT EXISTS frozen_at timestamp,
  ADD COLUMN IF NOT EXISTS frozen_by varchar(64),
  ADD COLUMN IF NOT EXISTS freeze_reason text,
  ADD COLUMN IF NOT EXISTS lock_status varchar(32) NOT NULL DEFAULT 'unlocked',
  ADD COLUMN IF NOT EXISTS lock_reason text,
  ADD COLUMN IF NOT EXISTS lock_operator_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS lock_operator_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS lock_operated_at timestamp;

ALTER TABLE plm_product_quality_record
  ADD COLUMN IF NOT EXISTS quality_issue_status varchar(32) NOT NULL DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS retest_result varchar(64),
  ADD COLUMN IF NOT EXISTS retest_at timestamp,
  ADD COLUMN IF NOT EXISTS frozen_at timestamp,
  ADD COLUMN IF NOT EXISTS frozen_by varchar(64),
  ADD COLUMN IF NOT EXISTS freeze_reason text,
  ADD COLUMN IF NOT EXISTS lock_status varchar(32) NOT NULL DEFAULT 'unlocked',
  ADD COLUMN IF NOT EXISTS lock_reason text,
  ADD COLUMN IF NOT EXISTS lock_operator_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS lock_operator_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS lock_operated_at timestamp;

ALTER TABLE plm_order_quote
  ADD COLUMN IF NOT EXISTS product_cost_version_no varchar(32),
  ADD COLUMN IF NOT EXISTS bom_version_no varchar(32),
  ADD COLUMN IF NOT EXISTS process_version_no varchar(32),
  ADD COLUMN IF NOT EXISTS cost_sync_status varchar(32) NOT NULL DEFAULT 'aligned',
  ADD COLUMN IF NOT EXISTS manual_estimate_flag bool_flag NOT NULL DEFAULT 0;

-- 2. Product variant uniqueness for SKU-like combinations under one parent.
CREATE UNIQUE INDEX IF NOT EXISTS uk_plm_product_variant_combination
ON plm_product (
  COALESCE(parent_product_id, 0),
  COALESCE(model, ''),
  COALESCE(color, ''),
  COALESCE(package_type, ''),
  COALESCE(customer_id, 0),
  version_no
)
WHERE deleted_flag = 0 AND product_type = 'model_variant';

-- 3. Tooling/fixture and workstation traceability.
ALTER TABLE plm_inventory
  ADD COLUMN IF NOT EXISTS current_workstation_id bigint REFERENCES plm_workstation(workstation_id),
  ADD COLUMN IF NOT EXISTS tooling_owner_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS tooling_owner_user_name varchar(128);

CREATE TABLE IF NOT EXISTS plm_inventory_workstation_binding (
  inventory_workstation_binding_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_id bigint NOT NULL REFERENCES plm_inventory(inventory_id),
  workstation_id bigint NOT NULL REFERENCES plm_workstation(workstation_id),
  bind_type varchar(32) NOT NULL DEFAULT 'install',
  bind_status varchar(32) NOT NULL DEFAULT 'active',
  installed_at timestamp,
  removed_at timestamp,
  remark text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by varchar(64) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(64) NOT NULL,
  deleted_flag bool_flag NOT NULL DEFAULT 0,
  CONSTRAINT ck_plm_inventory_workstation_binding_type CHECK (bind_type IN ('install', 'assignment', 'maintenance')),
  CONSTRAINT ck_plm_inventory_workstation_binding_status CHECK (bind_status IN ('active', 'inactive', 'removed')),
  CONSTRAINT ck_plm_inventory_workstation_binding_time CHECK (removed_at IS NULL OR installed_at IS NULL OR removed_at >= installed_at)
);

CREATE INDEX IF NOT EXISTS idx_plm_inventory_binding_inventory
ON plm_inventory_workstation_binding(inventory_id, bind_status);

CREATE INDEX IF NOT EXISTS idx_plm_inventory_binding_workstation
ON plm_inventory_workstation_binding(workstation_id, bind_status);

-- 4. Approval flow alignment with initiator/confirm separation and super admin intervention.
ALTER TABLE plm_approval_definition
  ADD COLUMN IF NOT EXISTS initiator_role_code varchar(64),
  ADD COLUMN IF NOT EXISTS confirmer_role_code varchar(64);

ALTER TABLE plm_approval_instance
  ADD COLUMN IF NOT EXISTS initiator_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS initiator_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS confirmer_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS confirmer_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS super_admin_action_flag bool_flag NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS super_admin_action_type varchar(32),
  ADD COLUMN IF NOT EXISTS super_admin_reason text,
  ADD COLUMN IF NOT EXISTS super_admin_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS super_admin_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS super_admin_action_at timestamp;

UPDATE plm_approval_instance
SET initiator_user_id = start_user_id
WHERE initiator_user_id IS NULL AND start_user_id IS NOT NULL;

UPDATE plm_approval_instance
SET status = 'completed'
WHERE status = 'approved';

ALTER TABLE plm_approval_task
  ADD COLUMN IF NOT EXISTS transferred_to_user_id bigint REFERENCES sys_user(user_id),
  ADD COLUMN IF NOT EXISTS transferred_to_user_name varchar(128),
  ADD COLUMN IF NOT EXISTS is_super_admin_action bool_flag NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS action_payload jsonb;

UPDATE plm_approval_task
SET action_type = 'cancelled'
WHERE action_type = 'cancel';

-- 5. Operation log alignment for super admin and lock actions.
ALTER TABLE plm_operation_log
  ADD COLUMN IF NOT EXISTS is_super_admin_action bool_flag NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS notify_management_flag bool_flag NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS request_id varchar(128),
  ADD COLUMN IF NOT EXISTS action_result varchar(32) NOT NULL DEFAULT 'success',
  ADD COLUMN IF NOT EXISTS action_comment text;

-- 6. Import and integration state machine alignment.
UPDATE plm_import_batch
SET status = 'in_progress'
WHERE status = 'confirmed';

UPDATE plm_import_detail
SET status = 'in_progress'
WHERE status = 'confirmed';

UPDATE plm_integration_log
SET status = 'in_progress'
WHERE status = 'confirmed';

ALTER TABLE plm_import_batch
  ADD COLUMN IF NOT EXISTS partial_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completed_at timestamp,
  ADD COLUMN IF NOT EXISTS closed_at timestamp;

ALTER TABLE plm_import_detail
  ADD COLUMN IF NOT EXISTS processed_at timestamp;

ALTER TABLE plm_integration_log
  ADD COLUMN IF NOT EXISTS next_retry_at timestamp,
  ADD COLUMN IF NOT EXISTS completed_at timestamp,
  ADD COLUMN IF NOT EXISTS manual_review_reason text;

-- 7. Constraint refresh.
ALTER TABLE plm_product
  DROP CONSTRAINT IF EXISTS ck_plm_product_status;
ALTER TABLE plm_product
  ADD CONSTRAINT ck_plm_product_status CHECK (status IN ('draft', 'developing', 'reviewing', 'released', 'archived'));

ALTER TABLE plm_process
  DROP CONSTRAINT IF EXISTS ck_plm_process_status;
ALTER TABLE plm_process
  ADD CONSTRAINT ck_plm_process_status CHECK (status IN ('draft', 'confirmed', 'locked', 'changed', 'archived'));

ALTER TABLE plm_product_bom
  DROP CONSTRAINT IF EXISTS ck_plm_product_bom_status;
ALTER TABLE plm_product_bom
  ADD CONSTRAINT ck_plm_product_bom_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'));

ALTER TABLE plm_attachment
  DROP CONSTRAINT IF EXISTS ck_plm_attachment_status;
ALTER TABLE plm_attachment
  ADD CONSTRAINT ck_plm_attachment_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'));

ALTER TABLE plm_product_quality_record
  DROP CONSTRAINT IF EXISTS ck_plm_product_quality_status;
ALTER TABLE plm_product_quality_record
  ADD CONSTRAINT ck_plm_product_quality_status CHECK (status IN ('draft', 'reviewing', 'released', 'archived'));

ALTER TABLE plm_product_quality_record
  ADD CONSTRAINT ck_plm_product_quality_issue_status CHECK (quality_issue_status IN ('normal', 'open', 'improving', 'closed', 'expired'));

ALTER TABLE plm_order_quote
  DROP CONSTRAINT IF EXISTS ck_plm_order_quote_status;
ALTER TABLE plm_order_quote
  ADD CONSTRAINT ck_plm_order_quote_status CHECK (status IN ('draft', 'confirmed', 'completed', 'closed'));

ALTER TABLE plm_order_quote
  ADD CONSTRAINT ck_plm_order_quote_cost_sync_status CHECK (cost_sync_status IN ('aligned', 'changed', 'manual_estimate'));

ALTER TABLE plm_product
  ADD CONSTRAINT ck_plm_product_lock_status CHECK (lock_status IN ('unlocked', 'frozen', 'super_admin_locked'));
ALTER TABLE plm_process
  ADD CONSTRAINT ck_plm_process_lock_status CHECK (lock_status IN ('unlocked', 'frozen', 'super_admin_locked'));
ALTER TABLE plm_product_bom
  ADD CONSTRAINT ck_plm_product_bom_lock_status CHECK (lock_status IN ('unlocked', 'frozen', 'super_admin_locked'));
ALTER TABLE plm_attachment
  ADD CONSTRAINT ck_plm_attachment_lock_status CHECK (lock_status IN ('unlocked', 'frozen', 'super_admin_locked'));
ALTER TABLE plm_product_quality_record
  ADD CONSTRAINT ck_plm_product_quality_lock_status CHECK (lock_status IN ('unlocked', 'frozen', 'super_admin_locked'));

ALTER TABLE plm_approval_instance
  DROP CONSTRAINT IF EXISTS ck_plm_approval_instance_status;
ALTER TABLE plm_approval_instance
  ADD CONSTRAINT ck_plm_approval_instance_status CHECK (
    status IN ('draft', 'in_progress', 'completed', 'rejected', 'cancelled', 'closed', 'super_admin_forced', 'super_admin_blocked')
  );

ALTER TABLE plm_approval_instance
  ADD CONSTRAINT ck_plm_approval_instance_super_admin_action CHECK (
    super_admin_action_type IS NULL OR super_admin_action_type IN ('forced', 'blocked', 'unlock', 'override_approve', 'override_reject')
  );

ALTER TABLE plm_approval_instance
  ADD CONSTRAINT ck_plm_approval_instance_initiator_confirmer CHECK (
    initiator_user_id IS NULL OR confirmer_user_id IS NULL OR initiator_user_id <> confirmer_user_id
  );

ALTER TABLE plm_approval_task
  DROP CONSTRAINT IF EXISTS ck_plm_approval_task_action_type;
ALTER TABLE plm_approval_task
  ADD CONSTRAINT ck_plm_approval_task_action_type CHECK (
    action_type IS NULL OR action_type IN ('approve', 'reject', 'transfer', 'cancelled', 'comment', 'force_approve', 'force_reject', 'force_block', 'emergency_unlock')
  );

ALTER TABLE plm_approval_task
  DROP CONSTRAINT IF EXISTS ck_plm_approval_task_status;
ALTER TABLE plm_approval_task
  ADD CONSTRAINT ck_plm_approval_task_status CHECK (
    status IN ('pending', 'approved', 'rejected', 'transferred', 'cancelled', 'super_admin_forced', 'super_admin_blocked')
  );

ALTER TABLE plm_operation_log
  DROP CONSTRAINT IF EXISTS ck_plm_operation_log_action;
ALTER TABLE plm_operation_log
  ADD CONSTRAINT ck_plm_operation_log_action CHECK (
    action_type IN (
      'create', 'update', 'delete', 'submit', 'approve', 'reject', 'freeze', 'publish', 'void',
      'download', 'import', 'retry', 'compensate', 'force_advance', 'force_block', 'emergency_unlock',
      'transfer', 'comment'
    )
  );

ALTER TABLE plm_operation_log
  ADD CONSTRAINT ck_plm_operation_log_result CHECK (action_result IN ('success', 'failed', 'partial'));

ALTER TABLE plm_import_batch
  DROP CONSTRAINT IF EXISTS ck_plm_import_batch_status;
ALTER TABLE plm_import_batch
  ADD CONSTRAINT ck_plm_import_batch_status CHECK (status IN ('draft', 'in_progress', 'completed', 'partial', 'closed', 'failed'));

ALTER TABLE plm_import_detail
  DROP CONSTRAINT IF EXISTS ck_plm_import_detail_status;
ALTER TABLE plm_import_detail
  ADD CONSTRAINT ck_plm_import_detail_status CHECK (status IN ('draft', 'in_progress', 'completed', 'failed', 'skipped'));

ALTER TABLE plm_integration_log
  DROP CONSTRAINT IF EXISTS ck_plm_integration_log_status;
ALTER TABLE plm_integration_log
  ADD CONSTRAINT ck_plm_integration_log_status CHECK (
    status IN ('draft', 'pending', 'in_progress', 'completed', 'failed', 'retrying', 'manual_review', 'closed')
  );

-- 8. Indexes for common workflow queries.
CREATE INDEX IF NOT EXISTS idx_plm_product_lock_status ON plm_product(lock_status, status);
CREATE INDEX IF NOT EXISTS idx_plm_process_lock_status ON plm_process(lock_status, status);
CREATE INDEX IF NOT EXISTS idx_plm_product_bom_lock_status ON plm_product_bom(lock_status, status);
CREATE INDEX IF NOT EXISTS idx_plm_attachment_lock_status ON plm_attachment(lock_status, status);
CREATE INDEX IF NOT EXISTS idx_plm_quality_issue_status ON plm_product_quality_record(quality_issue_status, status);
CREATE INDEX IF NOT EXISTS idx_plm_inventory_current_workstation ON plm_inventory(current_workstation_id);
CREATE INDEX IF NOT EXISTS idx_plm_approval_instance_initiator ON plm_approval_instance(initiator_user_id, status);
CREATE INDEX IF NOT EXISTS idx_plm_approval_instance_confirmer ON plm_approval_instance(confirmer_user_id, status);
CREATE INDEX IF NOT EXISTS idx_plm_operation_log_super_admin ON plm_operation_log(is_super_admin_action, created_at);
CREATE INDEX IF NOT EXISTS idx_plm_import_batch_status ON plm_import_batch(status, created_at);
CREATE INDEX IF NOT EXISTS idx_plm_integration_log_status_retry ON plm_integration_log(status, next_retry_at);

COMMENT ON TABLE plm_inventory_workstation_binding IS 'Inventory and Workstation install/assignment history for tooling and fixture traceability.';
COMMENT ON COLUMN plm_product.lock_status IS 'Explicit lock state for freeze and super-admin block scenarios.';
COMMENT ON COLUMN plm_process.released_at IS 'Release timestamp for versioned Process records.';
COMMENT ON COLUMN plm_approval_instance.initiator_user_id IS 'Workflow initiator used for separation-of-duties validation.';
COMMENT ON COLUMN plm_approval_instance.super_admin_action_type IS 'Super admin intervention type for audit and notification.';
COMMENT ON COLUMN plm_operation_log.is_super_admin_action IS 'High-risk operation marker for red highlighting and monthly audit reports.';
