spring:
  application:
    name: plm-server
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted_flag
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.yuewei.plm: info
